services:
  - type: web
    name: wp-site-inspector-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app
    envVars:
      - key: OPENROUTER_API_KEY
        value: your-api-key-here
