services:
  - type: web
    name: wp-site-inspector-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
